-- supabase/migrations/0001_initial_schema.sql
-- This SQL file contains the complete initial schema for the database.

-- USERS
-- Extends Supabase's built-in auth.users table.
CREATE TABLE users (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    full_name TEXT,
    avatar_url TEXT,
    subscription_tier TEXT DEFAULT 'free',
    credits INTEGER DEFAULT 10
);

-- AGENT WORKFLOWS
-- Stores workflows saved by users.
CREATE TABLE agent_workflows (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    name TEXT NOT NULL,
    workflow_definition JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- AGENT SESSIONS
-- Tracks each instance of a workflow being run.
CREATE TABLE agent_sessions (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    workflow_id INTEGER REFERENCES agent_workflows(id),
    status TEXT DEFAULT 'running', -- running, paused, completed, error
    context JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- AGENT OUTPUTS
-- Stores the final outputs generated by agent sessions.
CREATE TABLE agent_outputs (
    id SERIAL PRIMARY KEY,
    session_id INTEGER REFERENCES agent_sessions(id),
    output_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- BLOG POSTS
CREATE TABLE blog_posts (
    id SERIAL PRIMARY KEY,
    author_id UUID REFERENCES users(id),
    title TEXT NOT NULL,
    content TEXT,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- COURSES
CREATE TABLE courses (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    instructor_id UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- COURSE PROGRESS
CREATE TABLE course_progress (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    course_id INTEGER REFERENCES courses(id),
    progress INTEGER DEFAULT 0, -- Percentage
    UNIQUE(user_id, course_id)
);

-- COMMUNITY POSTS
CREATE TABLE community_posts (
    id SERIAL PRIMARY KEY,
    author_id UUID REFERENCES users(id),
    title TEXT NOT NULL,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- COMMUNITY THREADS
-- For replies to community posts
CREATE TABLE community_threads (
    id SERIAL PRIMARY KEY,
    post_id INTEGER REFERENCES community_posts(id),
    author_id UUID REFERENCES users(id),
    content TEXT,
    parent_thread_id INTEGER REFERENCES community_threads(id), -- For nested replies
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- DOWNLOADS
-- Marketplace for downloadable resources
CREATE TABLE downloads (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    file_url TEXT,
    price_credits INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TRANSACTIONS
-- Tracks credit usage and purchases
CREATE TABLE transactions (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    type TEXT NOT NULL, -- 'purchase', 'usage', 'refund'
    amount INTEGER NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- NOTIFICATIONS
CREATE TABLE notifications (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
